name: Validate PR
on:
  workflow_call:
  pull_request:
  pull_request_review:
    types: [ submitted ]

env:
  IMAGE_REPO: ${{ github.repository }}

jobs:
  validate-versions:
    name: "Check kubectl release versions"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - run: scripts/check-versions.sh
      - name: Find newest kubectl version
        run: |
          newest=$(head -n 1 versions.txt)
          echo "KUBECTL_VERSION=$newest" >> $GITHUB_ENV
      - name: Build image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        id: build-image
        with:
          context: .
          file: package/Dockerfile
          platforms: "linux/amd64"
          push: false
          load: true
          tags: ${{ env.IMAGE_REPO }}:${{ env.KUBECTL_VERSION }}-pr
          build-args: |
            KUBERNETES_RELEASE=${{ env.KUBECTL_VERSION }}
      - name: Unit test image
        run: scripts/unit-test-image.sh ${{ env.KUBECTL_VERSION }}-pr
        env:
          REPO: ${{ env.IMAGE_REPO }}