name: Validate PR
on:
  workflow_call:
  pull_request:
  pull_request_review:
    types: [ submitted ]
jobs:
  validate-versions:
    name: "Check kubectl release versions"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - run: scripts/check-versions.sh