name: Validate PR
on:
  workflow_call:
  pull_request:
  pull_request_review:
    types: [ submitted ]
jobs:
  validate-versions:
    name: "Check kubectl release versions"
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - run: scripts/check-versions.sh